server:
  port: 8093

spring:
  application:
    name: tipo-reclamo
  datasource:
    url: jdbc:mysql://localhost:3306/reclamos
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
client:
  service-url:
    defaultZone: http://localhost:8761/eureka